imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: v1
        connections:
            v1:
                driver:   "%database_driver_v1%"
                host:     "%database_host_v1%"
                port:     "%database_port_v1%"
                dbname:   "%database_name_v1%"
                user:     "%database_user_v1%"
                password: "%database_password_v1%"
                charset:  UTF8
            v2:
                driver:   "%database_driver_v2%"
                host:     "%database_host_v2%"
                port:     "%database_port_v2%"
                dbname:   "%database_name_v2%"
                user:     "%database_user_v2%"
                password: "%database_password_v2%"
                charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
#        auto_generate_proxy_classes:            "%kernel.debug%"
#        auto_mapping:                           true
        default_entity_manager:                 v1
        entity_managers:
            v1:
                connection:             v1
                mappings:
                    MutumV1Bundle:      ~
            v2:
                connection:             v2
                mappings:
                    MutumV2Bundle:      ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
