<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \Mutum\Bundle\V2Bundle\Entity\Message implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'messId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'user', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'messText', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'messDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'messClass', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'discussion');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'messId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'user', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'messText', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'messDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'messClass', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Message' . "\0" . 'discussion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Message $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMessId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMessId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessId', array());

        return parent::getMessId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessText($messText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessText', array($messText));

        return parent::setMessText($messText);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessText', array());

        return parent::getMessText();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessDateCreation($messDateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessDateCreation', array($messDateCreation));

        return parent::setMessDateCreation($messDateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessDateCreation', array());

        return parent::getMessDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessClass($messClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessClass', array($messClass));

        return parent::setMessClass($messClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessClass', array());

        return parent::getMessClass();
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscussion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscussion', array());

        return parent::getDiscussion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscussion(\Mutum\Bundle\V2Bundle\Entity\Discussion $discussion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscussion', array($discussion));

        return parent::setDiscussion($discussion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Mutum\Bundle\V2Bundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

}
