<?php

namespace Proxies\__CG__\Mutum\Bundle\V1Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PozAbuse extends \Mutum\Bundle\V1Bundle\Entity\PozAbuse implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseType', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseDestId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseTitle', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseText', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseCreated', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseAborded', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseSeen', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseArchived');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseType', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseDestId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseTitle', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseText', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseCreated', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseAborded', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseSeen', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozAbuse' . "\0" . 'abuseArchived');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PozAbuse $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAbuseId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAbuseId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseId', array());

        return parent::getAbuseId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbuseUserId($abuseUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbuseUserId', array($abuseUserId));

        return parent::setAbuseUserId($abuseUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbuseUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseUserId', array());

        return parent::getAbuseUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbuseType($abuseType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbuseType', array($abuseType));

        return parent::setAbuseType($abuseType);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbuseType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseType', array());

        return parent::getAbuseType();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbuseDestId($abuseDestId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbuseDestId', array($abuseDestId));

        return parent::setAbuseDestId($abuseDestId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbuseDestId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseDestId', array());

        return parent::getAbuseDestId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbuseTitle($abuseTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbuseTitle', array($abuseTitle));

        return parent::setAbuseTitle($abuseTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbuseTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseTitle', array());

        return parent::getAbuseTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbuseText($abuseText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbuseText', array($abuseText));

        return parent::setAbuseText($abuseText);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbuseText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseText', array());

        return parent::getAbuseText();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbuseCreated($abuseCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbuseCreated', array($abuseCreated));

        return parent::setAbuseCreated($abuseCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbuseCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseCreated', array());

        return parent::getAbuseCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbuseAborded($abuseAborded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbuseAborded', array($abuseAborded));

        return parent::setAbuseAborded($abuseAborded);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbuseAborded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseAborded', array());

        return parent::getAbuseAborded();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbuseSeen($abuseSeen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbuseSeen', array($abuseSeen));

        return parent::setAbuseSeen($abuseSeen);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbuseSeen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseSeen', array());

        return parent::getAbuseSeen();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbuseArchived($abuseArchived)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbuseArchived', array($abuseArchived));

        return parent::setAbuseArchived($abuseArchived);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbuseArchived()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbuseArchived', array());

        return parent::getAbuseArchived();
    }

}
