<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Research extends \Mutum\Bundle\V2Bundle\Entity\Research implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'user', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseText', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseLocation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'category', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseResults', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseIp', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'v1');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'user', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseText', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseLocation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'category', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseResults', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'reseIp', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Research' . "\0" . 'v1');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Research $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getReseId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getReseId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReseId', array());

        return parent::getReseId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Mutum\Bundle\V2Bundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setReseText($reseText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReseText', array($reseText));

        return parent::setReseText($reseText);
    }

    /**
     * {@inheritDoc}
     */
    public function getReseText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReseText', array());

        return parent::getReseText();
    }

    /**
     * {@inheritDoc}
     */
    public function setReseLocation($reseLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReseLocation', array($reseLocation));

        return parent::setReseLocation($reseLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getReseLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReseLocation', array());

        return parent::getReseLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Mutum\Bundle\V2Bundle\Entity\CategoryArticle $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function setReseResults($reseResults)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReseResults', array($reseResults));

        return parent::setReseResults($reseResults);
    }

    /**
     * {@inheritDoc}
     */
    public function getReseResults()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReseResults', array());

        return parent::getReseResults();
    }

    /**
     * {@inheritDoc}
     */
    public function setReseDateCreation($reseDateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReseDateCreation', array($reseDateCreation));

        return parent::setReseDateCreation($reseDateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getReseDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReseDateCreation', array());

        return parent::getReseDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setReseIp($reseIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReseIp', array($reseIp));

        return parent::setReseIp($reseIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getReseIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReseIp', array());

        return parent::getReseIp();
    }

    /**
     * {@inheritDoc}
     */
    public function getV1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getV1', array());

        return parent::getV1();
    }

    /**
     * {@inheritDoc}
     */
    public function setV1($v1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setV1', array($v1));

        return parent::setV1($v1);
    }

}
