<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CautionAsk extends \Mutum\Bundle\V2Bundle\Entity\CautionAsk implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaAmount', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaMotif', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaMessage', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaAskDate', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaCaurId');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaAmount', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaMotif', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaMessage', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaAskDate', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CautionAsk' . "\0" . 'cauaCaurId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CautionAsk $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCauaId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCauaId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCauaId', array());

        return parent::getCauaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCauaAmount($cauaAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCauaAmount', array($cauaAmount));

        return parent::setCauaAmount($cauaAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getCauaAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCauaAmount', array());

        return parent::getCauaAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCauaMotif($cauaMotif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCauaMotif', array($cauaMotif));

        return parent::setCauaMotif($cauaMotif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCauaMotif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCauaMotif', array());

        return parent::getCauaMotif();
    }

    /**
     * {@inheritDoc}
     */
    public function setCauaMessage($cauaMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCauaMessage', array($cauaMessage));

        return parent::setCauaMessage($cauaMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCauaMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCauaMessage', array());

        return parent::getCauaMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCauaAskDate($cauaAskDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCauaAskDate', array($cauaAskDate));

        return parent::setCauaAskDate($cauaAskDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCauaAskDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCauaAskDate', array());

        return parent::getCauaAskDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCauaCaurId($cauaCaurId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCauaCaurId', array($cauaCaurId));

        return parent::setCauaCaurId($cauaCaurId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCauaCaurId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCauaCaurId', array());

        return parent::getCauaCaurId();
    }

}
