<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Gift extends \Mutum\Bundle\V2Bundle\Entity\Gift implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftCode', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftAmount', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftNbValid', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftNbLeft', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftExpiration');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftCode', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftAmount', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftNbValid', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftNbLeft', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Gift' . "\0" . 'giftExpiration');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Gift $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getGiftId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getGiftId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftId', array());

        return parent::getGiftId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGiftCode($giftCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiftCode', array($giftCode));

        return parent::setGiftCode($giftCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftCode', array());

        return parent::getGiftCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setGiftAmount($giftAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiftAmount', array($giftAmount));

        return parent::setGiftAmount($giftAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftAmount', array());

        return parent::getGiftAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setGiftNbValid($giftNbValid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiftNbValid', array($giftNbValid));

        return parent::setGiftNbValid($giftNbValid);
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftNbValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftNbValid', array());

        return parent::getGiftNbValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGiftNbLeft($giftNbLeft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiftNbLeft', array($giftNbLeft));

        return parent::setGiftNbLeft($giftNbLeft);
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftNbLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftNbLeft', array());

        return parent::getGiftNbLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function setGiftDateCreation($giftDateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiftDateCreation', array($giftDateCreation));

        return parent::setGiftDateCreation($giftDateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftDateCreation', array());

        return parent::getGiftDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setGiftExpiration($giftExpiration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiftExpiration', array($giftExpiration));

        return parent::setGiftExpiration($giftExpiration);
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftExpiration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftExpiration', array());

        return parent::getGiftExpiration();
    }

}
