<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Session extends \Mutum\Bundle\V2Bundle\Entity\Session implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessSessionId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessRank', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessUrl', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessUserId');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessSessionId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessRank', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessUrl', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Session' . "\0" . 'sessUserId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Session $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setSessSessionId($sessSessionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessSessionId', array($sessSessionId));

        return parent::setSessSessionId($sessSessionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessSessionId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSessSessionId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessSessionId', array());

        return parent::getSessSessionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSessRank($sessRank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessRank', array($sessRank));

        return parent::setSessRank($sessRank);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessRank()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSessRank();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessRank', array());

        return parent::getSessRank();
    }

    /**
     * {@inheritDoc}
     */
    public function setSessDateCreation($sessDateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessDateCreation', array($sessDateCreation));

        return parent::setSessDateCreation($sessDateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessDateCreation', array());

        return parent::getSessDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setSessUrl($sessUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessUrl', array($sessUrl));

        return parent::setSessUrl($sessUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessUrl', array());

        return parent::getSessUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setSessUserId($sessUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessUserId', array($sessUserId));

        return parent::setSessUserId($sessUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessUserId', array());

        return parent::getSessUserId();
    }

}
