<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Speakers extends \Mutum\Bundle\V2Bundle\Entity\Speakers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'id', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'discussion', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'user', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'speaAdmin', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'speaSeen', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'speaArchived');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'id', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'discussion', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'user', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'speaAdmin', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'speaSeen', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Speakers' . "\0" . 'speaArchived');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Speakers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSpeaDiscId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeaDiscId', array());

        return parent::getSpeaDiscId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscussion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscussion', array());

        return parent::getDiscussion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscussion(\Mutum\Bundle\V2Bundle\Entity\Discussion $discussion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscussion', array($discussion));

        return parent::setDiscussion($discussion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Mutum\Bundle\V2Bundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeaAdmin($speaAdmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeaAdmin', array($speaAdmin));

        return parent::setSpeaAdmin($speaAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeaAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeaAdmin', array());

        return parent::getSpeaAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeaSeen($speaSeen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeaSeen', array($speaSeen));

        return parent::setSpeaSeen($speaSeen);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeaSeen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeaSeen', array());

        return parent::getSpeaSeen();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeaArchived($speaArchived)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeaArchived', array($speaArchived));

        return parent::setSpeaArchived($speaArchived);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeaArchived()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeaArchived', array());

        return parent::getSpeaArchived();
    }

}
