<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prolongation extends \Mutum\Bundle\V2Bundle\Entity\Prolongation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolRequId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolCredit', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolDate', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolMessage');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolRequId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolCredit', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolDate', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Prolongation' . "\0" . 'prolMessage');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Prolongation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProlId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProlId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProlId', array());

        return parent::getProlId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProlRequId($prolRequId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProlRequId', array($prolRequId));

        return parent::setProlRequId($prolRequId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProlRequId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProlRequId', array());

        return parent::getProlRequId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProlCredit($prolCredit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProlCredit', array($prolCredit));

        return parent::setProlCredit($prolCredit);
    }

    /**
     * {@inheritDoc}
     */
    public function getProlCredit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProlCredit', array());

        return parent::getProlCredit();
    }

    /**
     * {@inheritDoc}
     */
    public function setProlDate($prolDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProlDate', array($prolDate));

        return parent::setProlDate($prolDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getProlDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProlDate', array());

        return parent::getProlDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setProlMessage($prolMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProlMessage', array($prolMessage));

        return parent::setProlMessage($prolMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getProlMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProlMessage', array());

        return parent::getProlMessage();
    }

}
