<?php

namespace Proxies\__CG__\Mutum\Bundle\V1Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PozArticle extends \Mutum\Bundle\V1Bundle\Entity\PozArticle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artName', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artCatId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artPrice', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artLength', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artState', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artDesc', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artDispo', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artVisible', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artCaution', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artDates', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artPictures', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artAddress', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artZip', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artCity', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artLatitude', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artLongitude', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artWin', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artAdded', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artNotation', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artNbNotation', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artDeleted');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artName', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artCatId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artPrice', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artLength', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artState', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artDesc', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artDispo', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artVisible', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artCaution', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artDates', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artPictures', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artAddress', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artZip', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artCity', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artLatitude', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artLongitude', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artWin', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artAdded', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artNotation', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artNbNotation', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozArticle' . "\0" . 'artDeleted');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PozArticle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getArtId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getArtId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtId', array());

        return parent::getArtId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtUserId($artUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtUserId', array($artUserId));

        return parent::setArtUserId($artUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtUserId', array());

        return parent::getArtUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtName($artName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtName', array($artName));

        return parent::setArtName($artName);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtName', array());

        return parent::getArtName();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtCatId($artCatId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtCatId', array($artCatId));

        return parent::setArtCatId($artCatId);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtCatId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtCatId', array());

        return parent::getArtCatId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPrice($artPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPrice', array($artPrice));

        return parent::setArtPrice($artPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrice', array());

        return parent::getArtPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtLength($artLength)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtLength', array($artLength));

        return parent::setArtLength($artLength);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtLength', array());

        return parent::getArtLength();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtState($artState)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtState', array($artState));

        return parent::setArtState($artState);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtState', array());

        return parent::getArtState();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtDesc($artDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtDesc', array($artDesc));

        return parent::setArtDesc($artDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtDesc', array());

        return parent::getArtDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtDispo($artDispo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtDispo', array($artDispo));

        return parent::setArtDispo($artDispo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtDispo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtDispo', array());

        return parent::getArtDispo();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtVisible($artVisible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtVisible', array($artVisible));

        return parent::setArtVisible($artVisible);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtVisible', array());

        return parent::getArtVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtCaution($artCaution)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtCaution', array($artCaution));

        return parent::setArtCaution($artCaution);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtCaution()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtCaution', array());

        return parent::getArtCaution();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtDates($artDates)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtDates', array($artDates));

        return parent::setArtDates($artDates);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtDates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtDates', array());

        return parent::getArtDates();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPictures($artPictures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPictures', array($artPictures));

        return parent::setArtPictures($artPictures);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPictures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPictures', array());

        return parent::getArtPictures();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtAddress($artAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtAddress', array($artAddress));

        return parent::setArtAddress($artAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtAddress', array());

        return parent::getArtAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtZip($artZip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtZip', array($artZip));

        return parent::setArtZip($artZip);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtZip', array());

        return parent::getArtZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtCity($artCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtCity', array($artCity));

        return parent::setArtCity($artCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtCity', array());

        return parent::getArtCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtLatitude($artLatitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtLatitude', array($artLatitude));

        return parent::setArtLatitude($artLatitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtLatitude', array());

        return parent::getArtLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtLongitude($artLongitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtLongitude', array($artLongitude));

        return parent::setArtLongitude($artLongitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtLongitude', array());

        return parent::getArtLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtWin($artWin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtWin', array($artWin));

        return parent::setArtWin($artWin);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtWin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtWin', array());

        return parent::getArtWin();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtAdded($artAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtAdded', array($artAdded));

        return parent::setArtAdded($artAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtAdded', array());

        return parent::getArtAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtNotation($artNotation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtNotation', array($artNotation));

        return parent::setArtNotation($artNotation);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtNotation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtNotation', array());

        return parent::getArtNotation();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtNbNotation($artNbNotation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtNbNotation', array($artNbNotation));

        return parent::setArtNbNotation($artNbNotation);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtNbNotation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtNbNotation', array());

        return parent::getArtNbNotation();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtDeleted($artDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtDeleted', array($artDeleted));

        return parent::setArtDeleted($artDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtDeleted', array());

        return parent::getArtDeleted();
    }

}
