<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JoinCommunity extends \Mutum\Bundle\V2Bundle\Entity\JoinCommunity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'community', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'user', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'joinRank', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'joinStatus', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'joinDesc');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'community', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'user', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'joinRank', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'joinStatus', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\JoinCommunity' . "\0" . 'joinDesc');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (JoinCommunity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCommunity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommunity', array());

        return parent::getCommunity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommunity($community)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommunity', array($community));

        return parent::setCommunity($community);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUser();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setJoinRank($joinRank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoinRank', array($joinRank));

        return parent::setJoinRank($joinRank);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoinRank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoinRank', array());

        return parent::getJoinRank();
    }

    /**
     * {@inheritDoc}
     */
    public function setJoinStatus($joinStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoinStatus', array($joinStatus));

        return parent::setJoinStatus($joinStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoinStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoinStatus', array());

        return parent::getJoinStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setJoinDesc($joinDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoinDesc', array($joinDesc));

        return parent::setJoinDesc($joinDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoinDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoinDesc', array());

        return parent::getJoinDesc();
    }

}
