<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Solde extends \Mutum\Bundle\V2Bundle\Entity\Solde implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Solde' . "\0" . 'soldId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Solde' . "\0" . 'soldAmount', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Solde' . "\0" . 'soldDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Solde' . "\0" . 'soldUserId');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Solde' . "\0" . 'soldId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Solde' . "\0" . 'soldAmount', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Solde' . "\0" . 'soldDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Solde' . "\0" . 'soldUserId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Solde $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSoldId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSoldId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoldId', array());

        return parent::getSoldId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoldAmount($soldAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoldAmount', array($soldAmount));

        return parent::setSoldAmount($soldAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoldAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoldAmount', array());

        return parent::getSoldAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoldDateCreation($soldDateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoldDateCreation', array($soldDateCreation));

        return parent::setSoldDateCreation($soldDateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoldDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoldDateCreation', array());

        return parent::getSoldDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoldUserId($soldUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoldUserId', array($soldUserId));

        return parent::setSoldUserId($soldUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoldUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoldUserId', array());

        return parent::getSoldUserId();
    }

}
