<?php

namespace Proxies\__CG__\Mutum\Bundle\V1Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PozMessage extends \Mutum\Bundle\V1Bundle\Entity\PozMessage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgDestUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgArtId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgDatetime', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgText', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgReadFrom', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgReadDest', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgDeletedFrom', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgDeletedDest');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgDestUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgArtId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgDatetime', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgText', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgReadFrom', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgReadDest', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgDeletedFrom', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMessage' . "\0" . 'msgDeletedDest');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PozMessage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMsgId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMsgId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgId', array());

        return parent::getMsgId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgUserId($msgUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgUserId', array($msgUserId));

        return parent::setMsgUserId($msgUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgUserId', array());

        return parent::getMsgUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgDestUserId($msgDestUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgDestUserId', array($msgDestUserId));

        return parent::setMsgDestUserId($msgDestUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgDestUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgDestUserId', array());

        return parent::getMsgDestUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgArtId($msgArtId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgArtId', array($msgArtId));

        return parent::setMsgArtId($msgArtId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgArtId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgArtId', array());

        return parent::getMsgArtId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgDatetime($msgDatetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgDatetime', array($msgDatetime));

        return parent::setMsgDatetime($msgDatetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgDatetime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgDatetime', array());

        return parent::getMsgDatetime();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgText($msgText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgText', array($msgText));

        return parent::setMsgText($msgText);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgText', array());

        return parent::getMsgText();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgReadFrom($msgReadFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgReadFrom', array($msgReadFrom));

        return parent::setMsgReadFrom($msgReadFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgReadFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgReadFrom', array());

        return parent::getMsgReadFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgReadDest($msgReadDest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgReadDest', array($msgReadDest));

        return parent::setMsgReadDest($msgReadDest);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgReadDest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgReadDest', array());

        return parent::getMsgReadDest();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgDeletedFrom($msgDeletedFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgDeletedFrom', array($msgDeletedFrom));

        return parent::setMsgDeletedFrom($msgDeletedFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgDeletedFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgDeletedFrom', array());

        return parent::getMsgDeletedFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgDeletedDest($msgDeletedDest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgDeletedDest', array($msgDeletedDest));

        return parent::setMsgDeletedDest($msgDeletedDest);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgDeletedDest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgDeletedDest', array());

        return parent::getMsgDeletedDest();
    }

}
