<?php

namespace Proxies\__CG__\Mutum\Bundle\V1Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PozResearch extends \Mutum\Bundle\V1Bundle\Entity\PozResearch implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'id', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchText', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchCat', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchLocation', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchResults', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchCreated');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'id', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchText', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchCat', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchLocation', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchResults', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozResearch' . "\0" . 'researchCreated');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PozResearch $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResearchId($researchId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResearchId', array($researchId));

        return parent::setResearchId($researchId);
    }

    /**
     * {@inheritDoc}
     */
    public function getResearchId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResearchId', array());

        return parent::getResearchId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResearchText($researchText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResearchText', array($researchText));

        return parent::setResearchText($researchText);
    }

    /**
     * {@inheritDoc}
     */
    public function getResearchText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResearchText', array());

        return parent::getResearchText();
    }

    /**
     * {@inheritDoc}
     */
    public function setResearchCat($researchCat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResearchCat', array($researchCat));

        return parent::setResearchCat($researchCat);
    }

    /**
     * {@inheritDoc}
     */
    public function getResearchCat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResearchCat', array());

        return parent::getResearchCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setResearchLocation($researchLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResearchLocation', array($researchLocation));

        return parent::setResearchLocation($researchLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getResearchLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResearchLocation', array());

        return parent::getResearchLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setResearchResults($researchResults)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResearchResults', array($researchResults));

        return parent::setResearchResults($researchResults);
    }

    /**
     * {@inheritDoc}
     */
    public function getResearchResults()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResearchResults', array());

        return parent::getResearchResults();
    }

    /**
     * {@inheritDoc}
     */
    public function setResearchCreated($researchCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResearchCreated', array($researchCreated));

        return parent::setResearchCreated($researchCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getResearchCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResearchCreated', array());

        return parent::getResearchCreated();
    }

}
