<?php

namespace Proxies\__CG__\Mutum\Bundle\V1Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PozMove extends \Mutum\Bundle\V1Bundle\Entity\PozMove implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveDate', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveType', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveAmount');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveDate', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveType', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveUserId', '' . "\0" . 'Mutum\\Bundle\\V1Bundle\\Entity\\PozMove' . "\0" . 'moveAmount');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PozMove $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMoveId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMoveId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoveId', array());

        return parent::getMoveId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoveDate($moveDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoveDate', array($moveDate));

        return parent::setMoveDate($moveDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoveDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoveDate', array());

        return parent::getMoveDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoveType($moveType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoveType', array($moveType));

        return parent::setMoveType($moveType);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoveType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoveType', array());

        return parent::getMoveType();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoveUserId($moveUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoveUserId', array($moveUserId));

        return parent::setMoveUserId($moveUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoveUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoveUserId', array());

        return parent::getMoveUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoveAmount($moveAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoveAmount', array($moveAmount));

        return parent::setMoveAmount($moveAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoveAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoveAmount', array());

        return parent::getMoveAmount();
    }

}
