<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Caroussel extends \Mutum\Bundle\V2Bundle\Entity\Caroussel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroLimitation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroText', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroUserId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroWeight', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroDateFrom', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroDateTo');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroLimitation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroText', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroUserId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroWeight', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroDateFrom', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Caroussel' . "\0" . 'caroDateTo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Caroussel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCaroId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCaroId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaroId', array());

        return parent::getCaroId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaroLimitation($caroLimitation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaroLimitation', array($caroLimitation));

        return parent::setCaroLimitation($caroLimitation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaroLimitation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaroLimitation', array());

        return parent::getCaroLimitation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaroText($caroText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaroText', array($caroText));

        return parent::setCaroText($caroText);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaroText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaroText', array());

        return parent::getCaroText();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaroUserId($caroUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaroUserId', array($caroUserId));

        return parent::setCaroUserId($caroUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaroUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaroUserId', array());

        return parent::getCaroUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaroWeight($caroWeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaroWeight', array($caroWeight));

        return parent::setCaroWeight($caroWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaroWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaroWeight', array());

        return parent::getCaroWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaroDateFrom($caroDateFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaroDateFrom', array($caroDateFrom));

        return parent::setCaroDateFrom($caroDateFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaroDateFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaroDateFrom', array());

        return parent::getCaroDateFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaroDateTo($caroDateTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaroDateTo', array($caroDateTo));

        return parent::setCaroDateTo($caroDateTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaroDateTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaroDateTo', array());

        return parent::getCaroDateTo();
    }

}
