<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Request extends \Mutum\Bundle\V2Bundle\Entity\Request implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'lender', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'borrower', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'product', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDateFrom', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDateTo', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requProlId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requCredit', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDiscussion', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requCode', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requStatus', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requLenderNotaId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requBorrowerNotaId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requProdNote', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requLenderArchive', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requBorrowerArchive', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requLenderRead', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requBorrowerRead', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requCautId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDelete', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'v1', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'posts');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'lender', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'borrower', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'product', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDateFrom', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDateTo', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requProlId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requCredit', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDiscussion', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requCode', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requStatus', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requLenderNotaId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requBorrowerNotaId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requProdNote', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requLenderArchive', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requBorrowerArchive', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requLenderRead', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requBorrowerRead', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requCautId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'requDelete', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'v1', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Request' . "\0" . 'posts');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Request $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRequId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRequId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequId', array());

        return parent::getRequId();
    }

    /**
     * {@inheritDoc}
     */
    public function getBorrower()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBorrower', array());

        return parent::getBorrower();
    }

    /**
     * {@inheritDoc}
     */
    public function setBorrower($borrower)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBorrower', array($borrower));

        return parent::setBorrower($borrower);
    }

    /**
     * {@inheritDoc}
     */
    public function getLender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLender', array());

        return parent::getLender();
    }

    /**
     * {@inheritDoc}
     */
    public function setLender($lender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLender', array($lender));

        return parent::setLender($lender);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', array());

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\Mutum\Bundle\V2Bundle\Entity\Product $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', array($product));

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function setRequDateCreation($requDateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequDateCreation', array($requDateCreation));

        return parent::setRequDateCreation($requDateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequDateCreation', array());

        return parent::getRequDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequDateFrom($requDateFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequDateFrom', array($requDateFrom));

        return parent::setRequDateFrom($requDateFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequDateFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequDateFrom', array());

        return parent::getRequDateFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequDateTo($requDateTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequDateTo', array($requDateTo));

        return parent::setRequDateTo($requDateTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequDateTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequDateTo', array());

        return parent::getRequDateTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequProlId($requProlId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequProlId', array($requProlId));

        return parent::setRequProlId($requProlId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequProlId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequProlId', array());

        return parent::getRequProlId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequCredit($requCredit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequCredit', array($requCredit));

        return parent::setRequCredit($requCredit);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequCredit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequCredit', array());

        return parent::getRequCredit();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequDiscussion($requDiscussion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequDiscussion', array($requDiscussion));

        return parent::setRequDiscussion($requDiscussion);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequDiscussion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequDiscussion', array());

        return parent::getRequDiscussion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequCode($requCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequCode', array($requCode));

        return parent::setRequCode($requCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequCode', array());

        return parent::getRequCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequStatus($requStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequStatus', array($requStatus));

        return parent::setRequStatus($requStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequStatus', array());

        return parent::getRequStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequLenderNotaId($requLenderNotaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequLenderNotaId', array($requLenderNotaId));

        return parent::setRequLenderNotaId($requLenderNotaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequLenderNotaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequLenderNotaId', array());

        return parent::getRequLenderNotaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequBorrowerNotaId($requBorrowerNotaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequBorrowerNotaId', array($requBorrowerNotaId));

        return parent::setRequBorrowerNotaId($requBorrowerNotaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequBorrowerNotaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequBorrowerNotaId', array());

        return parent::getRequBorrowerNotaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequProdNote($requProdNote)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequProdNote', array($requProdNote));

        return parent::setRequProdNote($requProdNote);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequProdNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequProdNote', array());

        return parent::getRequProdNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequLenderArchive($requLenderArchive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequLenderArchive', array($requLenderArchive));

        return parent::setRequLenderArchive($requLenderArchive);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequLenderArchive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequLenderArchive', array());

        return parent::getRequLenderArchive();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequBorrowerArchive($requBorrowerArchive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequBorrowerArchive', array($requBorrowerArchive));

        return parent::setRequBorrowerArchive($requBorrowerArchive);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequBorrowerArchive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequBorrowerArchive', array());

        return parent::getRequBorrowerArchive();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequLenderRead($requLenderRead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequLenderRead', array($requLenderRead));

        return parent::setRequLenderRead($requLenderRead);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequLenderRead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequLenderRead', array());

        return parent::getRequLenderRead();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequBorrowerRead($requBorrowerRead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequBorrowerRead', array($requBorrowerRead));

        return parent::setRequBorrowerRead($requBorrowerRead);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequBorrowerRead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequBorrowerRead', array());

        return parent::getRequBorrowerRead();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequCautId($requCautId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequCautId', array($requCautId));

        return parent::setRequCautId($requCautId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequCautId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequCautId', array());

        return parent::getRequCautId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequDelete($requDelete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequDelete', array($requDelete));

        return parent::setRequDelete($requDelete);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequDelete', array());

        return parent::getRequDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function getV1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getV1', array());

        return parent::getV1();
    }

    /**
     * {@inheritDoc}
     */
    public function setV1($v1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setV1', array($v1));

        return parent::setV1($v1);
    }

}
