<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Discussion extends \Mutum\Bundle\V2Bundle\Entity\Discussion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'discId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'discAllGrantInvit', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'discDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'discName', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'messages');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'discId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'discAllGrantInvit', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'discDateCreation', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'discName', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\Discussion' . "\0" . 'messages');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Discussion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDiscId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getDiscId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscId', array());

        return parent::getDiscId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscAllGrantInvit($discAllGrantInvit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscAllGrantInvit', array($discAllGrantInvit));

        return parent::setDiscAllGrantInvit($discAllGrantInvit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscAllGrantInvit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscAllGrantInvit', array());

        return parent::getDiscAllGrantInvit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscDateCreation($discDateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscDateCreation', array($discDateCreation));

        return parent::setDiscDateCreation($discDateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscDateCreation', array());

        return parent::getDiscDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscName($discName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscName', array($discName));

        return parent::setDiscName($discName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscName', array());

        return parent::getDiscName();
    }

    /**
     * {@inheritDoc}
     */
    public function getMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessages', array());

        return parent::getMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessages($messages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessages', array($messages));

        return parent::setMessages($messages);
    }

    /**
     * {@inheritDoc}
     */
    public function addMessage(\Mutum\Bundle\V2Bundle\Entity\Message $message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessage', array($message));

        return parent::addMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessage(\Mutum\Bundle\V2Bundle\Entity\Message $message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessage', array($message));

        return parent::removeMessage($message);
    }

}
