<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NotificationCat extends \Mutum\Bundle\V2Bundle\Entity\NotificationCat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\NotificationCat' . "\0" . 'notcId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\NotificationCat' . "\0" . 'notcName', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\NotificationCat' . "\0" . 'mails');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\NotificationCat' . "\0" . 'notcId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\NotificationCat' . "\0" . 'notcName', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\NotificationCat' . "\0" . 'mails');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (NotificationCat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNotcId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotcId', array($id));

        return parent::setNotcId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotcId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNotcId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotcId', array());

        return parent::getNotcId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotcName($notcName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotcName', array($notcName));

        return parent::setNotcName($notcName);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotcName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotcName', array());

        return parent::getNotcName();
    }

    /**
     * {@inheritDoc}
     */
    public function getMails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMails', array());

        return parent::getMails();
    }

    /**
     * {@inheritDoc}
     */
    public function setMails($mails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMails', array($mails));

        return parent::setMails($mails);
    }

    /**
     * {@inheritDoc}
     */
    public function addMail(\Mutum\Bundle\V2Bundle\Entity\NotificationMail $mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMail', array($mail));

        return parent::addMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMail(\Mutum\Bundle\V2Bundle\Entity\NotificationMail $mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMail', array($mail));

        return parent::removeMail($mail);
    }

}
