<?php

namespace Proxies\__CG__\Mutum\Bundle\V2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CommunityAsk extends \Mutum\Bundle\V2Bundle\Entity\CommunityAsk implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaUserId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaFirstname', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaLastname', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaNumber', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaAddress', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaName', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaType', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaText', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaWant');
        }

        return array('__isInitialized__', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaUserId', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaFirstname', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaLastname', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaNumber', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaAddress', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaName', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaType', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaText', '' . "\0" . 'Mutum\\Bundle\\V2Bundle\\Entity\\CommunityAsk' . "\0" . 'comaWant');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CommunityAsk $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getComaId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getComaId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaId', array());

        return parent::getComaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setComaUserId($comaUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComaUserId', array($comaUserId));

        return parent::setComaUserId($comaUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getComaUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaUserId', array());

        return parent::getComaUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setComaFirstname($comaFirstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComaFirstname', array($comaFirstname));

        return parent::setComaFirstname($comaFirstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getComaFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaFirstname', array());

        return parent::getComaFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setComaLastname($comaLastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComaLastname', array($comaLastname));

        return parent::setComaLastname($comaLastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getComaLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaLastname', array());

        return parent::getComaLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setComaNumber($comaNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComaNumber', array($comaNumber));

        return parent::setComaNumber($comaNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getComaNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaNumber', array());

        return parent::getComaNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setComaAddress($comaAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComaAddress', array($comaAddress));

        return parent::setComaAddress($comaAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getComaAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaAddress', array());

        return parent::getComaAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setComaName($comaName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComaName', array($comaName));

        return parent::setComaName($comaName);
    }

    /**
     * {@inheritDoc}
     */
    public function getComaName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaName', array());

        return parent::getComaName();
    }

    /**
     * {@inheritDoc}
     */
    public function setComaType($comaType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComaType', array($comaType));

        return parent::setComaType($comaType);
    }

    /**
     * {@inheritDoc}
     */
    public function getComaType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaType', array());

        return parent::getComaType();
    }

    /**
     * {@inheritDoc}
     */
    public function setComaText($comaText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComaText', array($comaText));

        return parent::setComaText($comaText);
    }

    /**
     * {@inheritDoc}
     */
    public function getComaText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaText', array());

        return parent::getComaText();
    }

    /**
     * {@inheritDoc}
     */
    public function setComaWant($comaWant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComaWant', array($comaWant));

        return parent::setComaWant($comaWant);
    }

    /**
     * {@inheritDoc}
     */
    public function getComaWant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComaWant', array());

        return parent::getComaWant();
    }

}
